### ISSUE TITLE
cannot import name 'numpy' from 'matplotlib'

### ISSUE THREAD

**Issue by edhembo** [simpeg/simpeg#1502]
### Describe the issue:

when run the  code ' import simpeg.electromagnetics.time_domain as tdem' , the compile said that.
my python vision is 3.10.14 

### Reproducible code example:

```python
import numpy as np
import os
from matplotlib import pyplot as plt
```

### Error message:

```shell
ImportError                               Traceback (most recent call last)
Cell In[1], line 6
      3 from matplotlib import pyplot as plt
      5 from simpeg import maps
----> 6 import simpeg.electromagnetics.time_domain as tdem
      7 from simpeg.utils import plot_1d_layer_model
      9 write_output = False

File d:\ProgramData\anaconda3\envs\ptlearn\lib\site-packages\simpeg\electromagnetics\__init__.py:40
     38 from . import time_domain
     39 from . import frequency_domain
---> 40 from . import natural_source
     41 from . import analytics
     42 from . import utils

File d:\ProgramData\anaconda3\envs\ptlearn\lib\site-packages\simpeg\electromagnetics\natural_source\__init__.py:58
      1 """
      2 ==============================================================================
      3 Natural Source EM (:mod:`simpeg.electromagnetics.natural_source`)
   (...)
     55 
     56 """
---> 58 from . import utils
     59 from . import sources as Src
...
     13     contour=True,
     14 ):
     15     indUniFreq = np.where(freq == array["freq"])

ImportError: cannot import name 'numpy' from 'matplotlib' (d:\ProgramData\anaconda3\envs\ptlearn\lib\site-packages\matplotlib\__init__.py)
```

### Runtime information:

none

### Context for the issue:

The error is in simpeg/electromagnetics/natural_source/utils/plot_data_types.py
replace
from matplotlib import pyplot as plt, colors , numpy as np
to
from matplotlib import pyplot as plt, colors 
import numpy as np

**Comment by santisoler** [comment]
Hi @edhembo for opening this PR. 

Running `import simpeg.electromagnetics.time_domain as tdem` is currently working on my end, using SimPEG v0.22.0. The reproducible code example you pasted in your message doesn't reproduce the error: it is not importing `simpeg`, just `os`, `numpy` and `matplotlib`, so I'm afraid I cannot reproduce your error.
Could you paste the output you get if you run the following snippet?

```python
import simpeg
simpeg.Report()
import simpeg.electromagnetics.time_domain as tdem
```

Nonetheless, the import line you mentioned in `plot_data_types.py` should be changed as you suggested. It relies on matplotlib's `__init__.py` file importing numpy, which is not something guaranteed (as you seem to be experiencing) and it's prone to fail.

**Comment by edhembo** [comment]
Yes, it's just an occasional error, as you said it's related to the init file of matplotlib.
I apologize that I didn't paste the full import code in the example.
I don't have this problem when I use simpeg on my other computer, thanks for your reply and answer!

**Comment by santisoler** [comment]
Good to know it's working now. No need to apologize! You did raise a fair point to that import line, so thank you for that.
